# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

    
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'kamp-app'
  displayName: 'Npm Install'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'kamp-app'
    customCommand: 'test --watch=false --code-coverage'
  displayName: 'Npm test'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'kamp-app'
    customCommand: 'build --production'
  displayName: 'Npm build'

  
